### ISSUE TITLE
Reimplement connector to work with recent version of core

### ISSUE THREAD

**Issue by pimotte** [discipl/discipl-core-ipv8#1]
This connector is from the before-era and needs a major make-over to work with current core and comply with the base connector.

**Comment by n9iels** [comment]
The status of this issue can be found here: https://github.com/Quintor/discipl-core-ipv8/tree/refactor/reimplement-connector

The list below is a general overview of the work that I'am planning to do:
- Implement the `BaseConnector` interface and methods and make it compatible with https://github.com/discipl/core
- Update and configure tooling like Babel and Mocha to work with TypeScript
   - Write type declarations for the `BaseConnector`
- Implement integration tests with a running instance of IPv8 to verify compatibility and foresee API changes at there side
- Implement a E2E test to verify compatibility with https://github.com/discipl/core
